# Generated by Django 4.1 on 2023-04-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel_admin", "0002_event"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="date",),
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="rooms/image"),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_holiday",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
