# Generated by Django 4.1 on 2023-05-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel_admin", "0004_room_is_closed_for_holiday"),
    ]

    operations = [
        migrations.DeleteModel(name="Event",),
        migrations.RemoveField(model_name="room", name="is_closed_for_holiday",),
        migrations.AlterField(
            model_name="room",
            name="price",
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
