# Generated by Django 4.1 on 2023-05-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cat_hotel_admin",
            "0005_delete_event_remove_room_is_closed_for_holiday_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="cat",
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
