# Generated by Django 4.1 on 2023-05-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel_admin", "0006_room_cat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="cat",
            field=models.IntegerField(default=1, max_length=10, null=True),
        ),
    ]
