# Generated by Django 4.1 on 2023-06-23 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel_admin", "0008_alter_room_cat_alter_room_image_alter_room_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomeSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=django.utils.timezone.now, null=True),
                ),
                ("day_income", models.FloatField(default=0, null=True)),
                ("month_income", models.FloatField(default=0, null=True)),
                ("year_income", models.FloatField(default=0, null=True)),
                ("total_income", models.FloatField(default=0, null=True)),
            ],
            options={"verbose_name_plural": "Income Summaries",},
        ),
    ]
