# Generated by Django 4.1 on 2023-07-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel_admin", "0012_managewebpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="managewebpage",
            name="about_us",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="managewebpage",
            name="contact",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="managewebpage",
            name="location",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="managewebpage",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
