# Generated by Django 4.1 on 2023-07-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel_admin", "0013_alter_managewebpage_about_us_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="managewebpage", name="image3",),
        migrations.RemoveField(model_name="managewebpage", name="image4",),
        migrations.AlterField(
            model_name="managewebpage",
            name="image2",
            field=models.ImageField(null=True, upload_to="recommended_images/"),
        ),
    ]
