# Generated by Django 4.1 on 2023-07-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel_admin", "0015_managewebpage_title2"),
    ]

    operations = [
        migrations.AddField(
            model_name="managewebpage",
            name="description3",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="managewebpage",
            name="description4",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="managewebpage",
            name="title3",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="managewebpage",
            name="title4",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
