# Generated by Django 4.1 on 2023-07-12 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel_admin", "0016_managewebpage_description3_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManageWebpageFooter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_us", models.CharField(max_length=255, null=True)),
                ("location", models.CharField(max_length=255, null=True)),
                ("contact", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ManageWebpageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(null=True, upload_to="recommended_images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManageWebpageRecommend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ManageWebpageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                ("image", models.ImageField(null=True, upload_to="slideshow_images/")),
                ("description", models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(model_name="managewebpage", name="about_us",),
        migrations.RemoveField(model_name="managewebpage", name="contact",),
        migrations.RemoveField(model_name="managewebpage", name="description1",),
        migrations.RemoveField(model_name="managewebpage", name="description2",),
        migrations.RemoveField(model_name="managewebpage", name="description3",),
        migrations.RemoveField(model_name="managewebpage", name="description4",),
        migrations.RemoveField(model_name="managewebpage", name="image1",),
        migrations.RemoveField(model_name="managewebpage", name="image2",),
        migrations.RemoveField(model_name="managewebpage", name="location",),
        migrations.RemoveField(model_name="managewebpage", name="title",),
        migrations.RemoveField(model_name="managewebpage", name="title2",),
        migrations.RemoveField(model_name="managewebpage", name="title3",),
        migrations.RemoveField(model_name="managewebpage", name="title4",),
        migrations.AddField(
            model_name="managewebpage",
            name="Recommend",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cat_hotel_admin.managewebpagerecommend",
            ),
        ),
        migrations.AddField(
            model_name="managewebpage",
            name="footer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cat_hotel_admin.managewebpagefooter",
            ),
        ),
        migrations.AddField(
            model_name="managewebpage",
            name="image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cat_hotel_admin.managewebpageimage",
            ),
        ),
        migrations.AddField(
            model_name="managewebpage",
            name="section",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cat_hotel_admin.managewebpagesection",
            ),
        ),
    ]
