# Generated by Django 4.1 on 2023-07-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel_admin", "0017_managewebpagefooter_managewebpageimage_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="ManageWebpage",),
    ]
