# Generated by Django 4.1 on 2023-07-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel_admin", "0018_delete_managewebpage"),
    ]

    operations = [
        migrations.DeleteModel(name="ManageWebpageFooter",),
        migrations.DeleteModel(name="ManageWebpageSection",),
    ]
