# Generated by Django 4.1 on 2023-07-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel_admin", "0019_delete_managewebpagefooter_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="ManageWebpageImage",),
        migrations.DeleteModel(name="ManageWebpageRecommend",),
    ]
