# Generated by Django 4.1 on 2023-07-12 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel_admin", "0021_admin_delete_admin_c"),
    ]

    operations = [
        migrations.DeleteModel(name="Admin",),
    ]
