# Generated by Django 4.1 on 2023-07-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel_admin", "0022_delete_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_number",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
