# Generated by Django 4.1 on 2023-04-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="phone_number",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
