# Generated by Django 4.1 on 2023-05-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel", "0002_alter_booking_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking", old_name="request_status", new_name="ended_status",
        ),
        migrations.RenameField(
            model_name="booking", old_name="reserved_status", new_name="staying_status",
        ),
    ]
