# Generated by Django 4.1 on 2023-05-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel", "0003_rename_request_status_booking_ended_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="booking", name="ended_status",),
    ]
