# Generated by Django 4.1 on 2023-05-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel", "0005_bookinghistory_checked_out"),
    ]

    operations = [
        migrations.RemoveField(model_name="bookinghistory", name="booking",),
        migrations.AddField(
            model_name="bookinghistory",
            name="cat",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="bookinghistory",
            name="cat_name",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="bookinghistory",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="bookinghistory",
            name="phone_number",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="bookinghistory",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
