# Generated by Django 4.1 on 2023-05-07 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel_admin", "0004_room_is_closed_for_holiday"),
        ("cat_hotel", "0006_remove_bookinghistory_booking_bookinghistory_cat_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review", old_name="customer_r", new_name="customer",
        ),
        migrations.AddField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cat_hotel_admin.room",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review", unique_together={("customer", "room")},
        ),
        migrations.RemoveField(model_name="review", name="booking_r",),
    ]
