# Generated by Django 4.1 on 2023-05-14 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "cat_hotel",
            "0007_rename_customer_r_review_customer_review_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="booking", name="cat",),
    ]
