# Generated by Django 4.1 on 2023-05-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel", "0008_remove_booking_cat"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="confirm_status",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
