# Generated by Django 4.1 on 2023-07-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel", "0013_alter_booking_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="total_price",
            field=models.IntegerField(null=True),
        ),
    ]
