# Generated by Django 4.1 on 2023-07-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel", "0014_booking_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="waiting_confirm",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
