# Generated by Django 4.1 on 2023-07-23 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel", "0015_booking_waiting_confirm"),
    ]

    operations = [
        migrations.CreateModel(
            name="CancellationReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason_text", models.TextField()),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cat_hotel.booking",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Review",),
    ]
