# Generated by Django 4.1 on 2023-07-23 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cat_hotel_admin", "0022_delete_admin"),
        ("cat_hotel", "0016_cancellationreason_delete_review"),
    ]

    operations = [
        migrations.RemoveField(model_name="cancellationreason", name="booking",),
        migrations.AddField(
            model_name="cancellationreason",
            name="cat",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cancellationreason",
            name="cat_name",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="cancellationreason",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cancellationreason",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="cancellationreason",
            name="phone_number",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="cancellationreason",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cat_hotel_admin.room",
            ),
        ),
        migrations.AddField(
            model_name="cancellationreason",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
