# Generated by Django 4.1 on 2023-07-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cat_hotel", "0018_booking_cat"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinghistory",
            name="total_price",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cancellationreason",
            name="total_price",
            field=models.IntegerField(null=True),
        ),
    ]
